[package]
name = "lunara-core"
version = "0.1.0"
edition = "2025"
license = "MIT OR Apache-2.0"
description = "Core library for Lunara: a safe, repeatable, multi-language workflow tool."
repository = ""

[lib]
path = "src/lib.rs"

[dependencies]

